### ISSUE TITLE
[Bug]: JWK thumbprint includes optional members when calculated

### ISSUE THREAD

**Issue by trew** [AxisCommunications/go-dpop#7]
### Describe the bug

When a DPoP is parsed, the JWK thumbprint should only include required members when calculated. See https://datatracker.ietf.org/doc/html/rfc7638#section-3.2

Related lines of code:
https://github.com/AxisCommunications/go-dpop/blob/e3feea2490d9593bff6ca6a73dd5548219e2f3aa/parse.go#L124-L137

### Steps to reproduce the behavior

Create a proof with a JWK containing optional fields, for example:

```
{
  "crv": "P-256",
  "ext": true,
  "kty": "EC",
  "x": "KDVM3aXrYGUgmKyo0q__DdIDVS0AV139ZTba04SKqFQ",
  "y": "SC-oR4qLdhmwrjr6PjJ7_LfFpC_BSFUT14LnMtgjHPs"
}
```

In this example, "ext" should be excluded.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SalladinBalwer** [comment]
This is indeed a bug and should be fixed.
I will look at it when I have time unless any one else claims it.
